/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static support.fileGenerator.FileCabinet;

/**
 *
 * @author Jordan Rog
 */
public class main extends javax.swing.JFrame {

    DefaultListModel m_listModel;
    int index = 0;
    int m_currentIndex = 0;
    boolean m_isEditable  = false;
    boolean m_listSelected= false;
    List<String> m_name   = new ArrayList<>();
    List<String> m_link   = new ArrayList<>();;
    List<String> m_price  = new ArrayList<>();;
    List<String> m_comment= new ArrayList<>();;
    /**
     * Creates new form main
     */
    public main() {
        m_reset();
        initComponents();
        m_setEditable(false);
    }
    
    private void m_reset(){
        m_listModel = new  DefaultListModel();
        m_name.clear();
        m_link.clear();
        m_price.clear();
        m_comment.clear();
    }
    private void m_displayVariables(int selectedIndex){
        if(-1 != selectedIndex){
            m_textBoxName   .setText(m_name.get(selectedIndex));
            m_textBoxPrice  .setText(m_price.get(selectedIndex));
            m_textBoxLink   .setText(m_link.get(selectedIndex));
            m_textBoxComment.setText(m_comment.get(selectedIndex));
            m_currentIndex = selectedIndex;
            m_listSelected  = true;
        }else{
            m_textBoxName.setText("");
            m_listSelected = false;
        }
    }
    
    private void m_setEditable(boolean answer){
        m_textBoxName   .setEditable(answer);
        m_textBoxPrice  .setEditable(answer);
        m_textBoxLink   .setEditable(answer);
        m_textBoxComment.setEditable(answer);
        
        m_textBoxName   .setFocusable(answer);
        m_textBoxPrice  .setFocusable(answer);
        m_textBoxLink   .setFocusable(answer);
        m_textBoxComment.setFocusable(answer);
        m_btnUpdate.setEnabled(answer && m_listSelected);
        m_isEditable = answer;
        if(!answer){
            m_displayVariables(m_list.getSelectedIndex());
        }
    }
    
    private void m_toggleEditable(){
       m_isEditable = !m_isEditable;
       m_setEditable(m_isEditable);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        m_list = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        m_textBoxName = new javax.swing.JTextField();
        m_labelName = new javax.swing.JLabel();
        m_btnUpdate = new javax.swing.JButton();
        m_btnEdit = new javax.swing.JButton();
        m_textBoxPrice = new javax.swing.JTextField();
        m_labelPrice = new javax.swing.JLabel();
        m_textBoxLink = new javax.swing.JTextField();
        m_labelLink = new javax.swing.JLabel();
        m_labelComment = new javax.swing.JLabel();
        m_textBoxComment = new javax.swing.JTextField();
        m_btnAddRow = new javax.swing.JButton();
        m_btnDeleteRow = new javax.swing.JButton();
        m_btnGenerateCode = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rows");
        setResizable(false);

        m_list.setModel(m_listModel);
        m_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        m_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(m_list);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        m_labelName.setText("Item Name");

        m_btnUpdate.setText("Update");
        m_btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnUpdateActionPerformed(evt);
            }
        });

        m_btnEdit.setText("Edit");
        m_btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnEditActionPerformed(evt);
            }
        });

        m_labelPrice.setText("Item Price");

        m_labelLink.setText("Item Link");

        m_labelComment.setText("Item Comment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 317, Short.MAX_VALUE)
                        .addComponent(m_btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_btnUpdate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m_labelName)
                            .addComponent(m_labelPrice)
                            .addComponent(m_labelLink)
                            .addComponent(m_labelComment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(m_textBoxLink)
                            .addComponent(m_textBoxPrice)
                            .addComponent(m_textBoxName)
                            .addComponent(m_textBoxComment, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_textBoxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_labelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_textBoxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_labelPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_textBoxLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_labelLink))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_textBoxComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_labelComment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_btnUpdate)
                    .addComponent(m_btnEdit))
                .addContainerGap())
        );

        m_btnAddRow.setText("Add Row");
        m_btnAddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnAddRowActionPerformed(evt);
            }
        });

        m_btnDeleteRow.setText("Delete Row");
        m_btnDeleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnDeleteRowActionPerformed(evt);
            }
        });

        m_btnGenerateCode.setText("Generate Code");
        m_btnGenerateCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnGenerateCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(m_btnDeleteRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_btnAddRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(m_btnGenerateCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m_btnAddRow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_btnDeleteRow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_btnGenerateCode)
                        .addGap(3, 3, 3)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_btnAddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnAddRowActionPerformed
        // TODO add your handling code here:
        
        m_name      .add(index, JOptionPane.showInputDialog("What shall I call this item?"));
        m_price     .add(index, JOptionPane.showInputDialog("If I may, how much did it cost you?"));
        m_link      .add(index, JOptionPane.showInputDialog("A link to this product would be much apprieciated."));
        m_comment   .add(index, JOptionPane.showInputDialog("Do you have any comments on the product?"));
        
//        System.out.println(m_name .get(index));
//        System.out.println(m_price.get(index));
//        System.out.println(m_link .get(index));
        
        if(m_comment.get(index).toUpperCase().equals("NO")){
            m_comment.set(index, "");
        }
        
        m_listModel.add(index, m_name.get(index));
        index++;
    }//GEN-LAST:event_m_btnAddRowActionPerformed

    private void m_btnDeleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnDeleteRowActionPerformed
        // TODO add your handling code here:
        int selectedIndex = m_list.getSelectedIndex();
        if (selectedIndex != -1) {
            m_listModel .remove(selectedIndex);
            m_name      .remove(selectedIndex);
            m_price     .remove(selectedIndex);
            m_link      .remove(selectedIndex);
            m_comment   .remove(selectedIndex);            
        } else {
//            System.out.println("Nothing selected");
        }
    }//GEN-LAST:event_m_btnDeleteRowActionPerformed

    private void m_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_listMouseClicked
        // TODO add your handling code here:
        int selectedIndex = m_list.getSelectedIndex();
        if(-1 != selectedIndex){
            m_setEditable(false);
        } else {
//            System.out.println("Nothing selected");
        }
        
    }//GEN-LAST:event_m_listMouseClicked

    private void m_btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnEditActionPerformed
        // TODO add your handling code here:
        m_toggleEditable();
    }//GEN-LAST:event_m_btnEditActionPerformed

    private void m_btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnUpdateActionPerformed
        // TODO add your handling code here:
        m_name      .set(m_currentIndex,m_textBoxName   .getText());
        m_price     .set(m_currentIndex,m_textBoxPrice  .getText());
        m_link      .set(m_currentIndex,m_textBoxLink   .getText());
        m_comment   .set(m_currentIndex,m_textBoxComment.getText());
        m_listModel .set(m_currentIndex,m_name.get(m_currentIndex));        
    }//GEN-LAST:event_m_btnUpdateActionPerformed

    private void m_btnGenerateCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnGenerateCodeActionPerformed
        FileCabinet.generateFile(m_name,m_price,m_link,m_comment);
    }//GEN-LAST:event_m_btnGenerateCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton m_btnAddRow;
    private javax.swing.JButton m_btnDeleteRow;
    private javax.swing.JButton m_btnEdit;
    private javax.swing.JButton m_btnGenerateCode;
    private javax.swing.JButton m_btnUpdate;
    private javax.swing.JLabel m_labelComment;
    private javax.swing.JLabel m_labelLink;
    private javax.swing.JLabel m_labelName;
    private javax.swing.JLabel m_labelPrice;
    private javax.swing.JList m_list;
    private javax.swing.JTextField m_textBoxComment;
    private javax.swing.JTextField m_textBoxLink;
    private javax.swing.JTextField m_textBoxName;
    private javax.swing.JTextField m_textBoxPrice;
    // End of variables declaration//GEN-END:variables
}
